name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml
        coverage: pcov
        tools: phpunit

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --coverage-clover clover.xml
      # Сохраните код выхода PHPUnit, чтобы использовать его в следующем шаге
      continue-on-error: true

    - name: Setup Code Climate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Upload coverage to Code Climate
      run: |
        EXIT_CODE=${{ steps.tests.outcome }}
        if [ $EXIT_CODE == "success" ]; then
          ./cc-test-reporter after-build --exit-code 0 -t clover --id ${{ secrets.CC_TEST_REPORTER_ID }} --coverage-input-type clover
        else
          ./cc-test-reporter after-build --exit-code 1 -t clover --id ${{ secrets.CC_TEST_REPORTER_ID }} --coverage-input-type clover
        fi
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
